export const accountPlan = Object.freeze([
  { number: "1000", name: "Kasse" },
  { number: "1020", name: "Bank" },
  { number: "1021", name: "Post" },
  { number: "1100", name: "Forderungen LL" },
  { number: "1140", name: "Darlehensforderungen" },
  { number: "1200", name: "Warenbestand" },
  { number: "1500", name: "Maschinen" },
  { number: "1510", name: "Mobiliar" },
  { number: "1520", name: "Büromaschinen" },
  { number: "1530", name: "Fahrzeuge" },
  { number: "1540", name: "Werkzeuge" },
  { number: "2000", name: "Verbindlichkeiten LL" },
  { number: "2100", name: "Bankkontokorrent" },
  { number: "2108", name: "Hypothek kurzfristig" },
  { number: "2140", name: "Bankdarlehen" },
  { number: "2450", name: "Darlehen" },
  { number: "2451", name: "Hypothek langfristig" },
  { number: "3000", name: "Produktionserlöse" },
  { number: "3200", name: "Warenertrag" },
  { number: "3400", name: "Dienstleistungsertrag" },
  { number: "4000", name: "Materialaufwand" },
  { number: "4200", name: "Warenaufwand" },
  { number: "6000", name: "Raumaufwand" },
  { number: "6100", name: "Unterhalt und Reparaturen" },
  { number: "6200", name: "Fahrzeugaufwand" },
  { number: "6300", name: "Versicherungsaufwand" },
  { number: "6570", name: "Informatikaufwand" },
  { number: "6700", name: "Sonstiger Betriebsaufwand" },
  { number: "6900", name: "Finanzaufwand" },
  { number: "6950", name: "Finanzertrag" },
]);
